version: "3.4"

services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    #environment:
    #    SERVE_PATH: /usr/src/servePath
    #    PORT: 8080
    volumes:
      - /home/kevin/Books/:${SERVE_PATH}
    ports:
      - 8000:${PORT}
    restart: unless-stopped
